### PR TITLE
Generic Get API call function and code generator for simple Get-* functions

### PR DESCRIPTION
**Pull request by dbroeglin**
This is not yet a PR, just a proposal to discuss. 

When correcting the Get-* methods I saw there is a pattern in most Get-* methods. This is my first attempt at extracting it and reusing it for `Get-NSResponderPolicy`. What do you think ?

### CODE REVIEW

**Comment by devblackops** [comment]
That makes sense to me. I'm all for having it reuse as much common code as possible.

**Comment by dbroeglin** [comment]
I added a simple code generator that generates Get-* functions that use the generic API call. The only thing that changes from one Get to another is the name, type, labels and the list of filter parameters so it works OK. 

As this is quite tedious work, so I would like to gather a bit of feedback before moving forward. What do you think about the current state ? Get-NSCSAction and Get-NSCSPolicy are completed.

**Comment by devblackops** [comment]
Sorry I didn't respond sooner. I think these are fantastic!

**Comment by dbroeglin** [comment]
Well thx ;-) I will continue with the ones I currently need for my project and then cleanup the PR.

**Comment by devblackops** [comment]
Sound good.

**Comment by dbroeglin** [comment]
I think this should do for now. It is ready for merge if you are OK with it.
I rebased everything on current master and squashed a couple commits. I have tried all cmdlets at least once, most are currently in use in scripts I run on a regular basis in my lab. So it is as tested as I can make it for now. One of my next steps will be to create system tests, but this is still cooking.

**Pull request merged**
